
name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write           # needed to create Releases
jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: fax-cshad.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
     
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x


    - name: Restore dependencies
      run: dotnet restore
    
    - name: Publish
      run: dotnet publish -c ${{ matrix.configuration }} --property:PublishDir=${{ env.PUB_DIR }}

    - name: Zip published output
      run: |
        if (Test-Path $Env:ZIP_NAME) { Remove-Item $Env:ZIP_NAME -Force }
        Compress-Archive -Path "${{ env.PUB_DIR }}\*" -DestinationPath $Env:ZIP_NAME
      shell: pwsh

    - name: Upload CI artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}-publish
        path: ${{ env.ZIP_NAME }}

      # Create GitHub Release and attach the zip *only* on tag pushes
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ZIP_NAME }}
        draft: false
        prerelease: false      

